### ISSUE TITLE
Param.state is never modified, resulting in stale cachign in Bijector and inplace modification errors in autograd

### ISSUE THREAD

**Issue by feynmanliang** [stefanwebb/simplex#5]
Expected: When I call `backward`s on the result of `Bijector.forward` after taking a `optimizer.step()` on the bijector's `params` using the same inputs `x`, I expect a new value of `y` to be computed using `x` and the updated `params`.

Actual: Since `Params.state` is never incremented, cache invalidation based on `state_cache` will never occur. When we try to back-propagate through a `y` whose parameters have already been `optim.step()`ed, we get

```
>       Variable._execution_engine.run_backward(
            tensors, grad_tensors_, retain_graph, create_graph,
            allow_unreachable=True)  # allow_unreachable flag
E       RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py:130: RuntimeError
```

**Comment by stefanwebb** [comment]
Hmm I'm not sure how to solve this one... Do you know how/where we could put in a hook so that `Params.state` is changed when you call `backwards` or update the parameters?

**Comment by feynmanliang** [comment]
We could look at `Tensor.register_hook`, but IMO it may be a bit early to
implement caching since that gets tricky quickly. We could just recompute
it for now and move forwards while keeping in mind practices (eg
referential transparency) to enable easier caching?

**Comment by stefanwebb** [comment]
Yes let's disable for now
