### ISSUE TITLE
scalar base_distributions are not well supported

### ISSUE THREAD

**Issue by feynmanliang** [stefanwebb/simplex#6]
Expected: AffineAutoregressive(DenseAutoregressive) should be able to use a scalar `base_distribution`

Actual: When using a `dist.Normal(0, 1)` base distribution, we get the error:

```
        # Shape the output
>       h = h.reshape(x.size()[:-len(self.input_shape)] + (self.output_multiplier, self.input_dims))
E       RuntimeError: shape '[2, 1]' is invalid for input of size 200

../simplex/simplex/params/dense_autoregressive.py:198: RuntimeError
```

RC: In particular, for scalar distributions both `batch_shape` and `event_shape` are `torch.Size([])` which is `len` zero, whereas a bit of `DenseAutoregressive.{_build,_forward}` seems to assume at least one of them is nonempty (so `Param.input_shape` is nonempty). We should modify this code to handle the special case `batch_dim == event_dim == torch.Size([])`.

**Comment by stefanwebb** [comment]
Thanks for catching that! Yes, let's make that change :)

**Comment by stefanwebb** [comment]
This could be a special case for the unit tests too
